// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_0xM6eKh8nRf3HYbTt63cAlSz9W8JhJM',
    appId: '1:1042375896756:web:e764848f448e6ff00ef1e1',
    messagingSenderId: '1042375896756',
    projectId: 'saglik-asistani-ef411',
    authDomain: 'saglik-asistani-ef411.firebaseapp.com',
    storageBucket: 'saglik-asistani-ef411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFpd6C-oTpBozWRXV_eqME269wp6aeL-g',
    appId: '1:1042375896756:android:8c4187dd4297b9fc0ef1e1',
    messagingSenderId: '1042375896756',
    projectId: 'saglik-asistani-ef411',
    storageBucket: 'saglik-asistani-ef411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBVoHxfkbGlt1a0-B6Uk3okuTL4jK-S4',
    appId: '1:1042375896756:ios:bf38fff30ed41f610ef1e1',
    messagingSenderId: '1042375896756',
    projectId: 'saglik-asistani-ef411',
    storageBucket: 'saglik-asistani-ef411.appspot.com',
    iosBundleId: 'com.example.saglikAsistani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBVoHxfkbGlt1a0-B6Uk3okuTL4jK-S4',
    appId: '1:1042375896756:ios:2059955e7a24894a0ef1e1',
    messagingSenderId: '1042375896756',
    projectId: 'saglik-asistani-ef411',
    storageBucket: 'saglik-asistani-ef411.appspot.com',
    iosBundleId: 'com.example.saglikAsistani.RunnerTests',
  );
}
